### ISSUE TITLE
output.heka_tcp is stuck retrying a message

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/hindsight#39]
For some reason, my heka_tcp output plugin is stuck retrying the same message from the input queue. Here is the log message that hindsight returns: `debug] output.heka_tcp retry message 32534755224530123 err: �K`

And here is the complete hindsight log since the error occured for the first time:
https://framabin.org/?2b64b85db214b22b#1TG684o58DV8HenPisQSNwW/3sh1FJy1fruUqKA5wR4=

The problematic input log file is attached (`6008.log`) as well as the `hindsight.tsv` and `hindsight.cp` checkpoint file: [hs_debug.zip](https://github.com/trink/hindsight/files/360961/hs_debug.zip)

**Comment by bbinet** [comment]
Note that when I simply stop and restart hindsight (while keeping both the `hindsight.cp` checkpoint file and the input log files), the issue was fixed, which is surprising because I thought it would read the same buggy heka message again and reproduce the issue.

**Comment by trink** [comment]
It sounds like a client connection couldn't be re-established and it was just thrashing here:
```lua 
if not client then return -3, err end -- retry indefinitely
```
But  the sequence identifier indicates memory corruption. I will do a quick code review.  On a related note the current lua_sandbox (actually lua_sandbox_extensions now) pulls in a much newer version of the socket and ssl library with many bug fixes, so that is worth trying.   FYI: All the extensions (modules and sandboxes) are now created as separate packages so they can be maintained/upgraded/deployed independently.  For convenience I have grouped the extensions Mozilla uses here:  https://github.com/mozilla-services/lua_sandbox_extensions/ but they can now live anywhere and work consistently (no more special built-ins modules or updating the core library for business logic changes)

**Comment by bbinet** [comment]
Thanks this sounds good!
I'd may try to create a LuaFileSystem (LFS) lua_sandbox extension which I often need in my sandboxes: should I host it myself of create a pull request  to the https://github.com/mozilla-services/lua_sandbox_extensions/ repository?

**Comment by trink** [comment]
Either way is fine but I won't be a bottleneck if you use your own repo (I will be happy to review it in either case).  In the end I will just hopefully yum install it when I need it and not be concerned with the repo :)

**Comment by trink** [comment]
@bbinet have you been able to reproduce this with the latest packages?

**Comment by bbinet** [comment]
I'm currently in the process of upgrading to the latest packages, but this is not functional yet.

Note that I've still not reproduced this issue with the old Hindsight version I'm using.

**Comment by trink** [comment]
Reopen if you can reproduce it as the heka_tcp output was reworked since this time
https://github.com/mozilla-services/lua_sandbox_extensions/commit/90144b5cf80b640e69768f506ff0f8903a92be81
